baseURL = "."
languageCode = "en-us"
title = "Time Fluid Field Based Coordination"
theme = "reveal-hugo"
relativeURLs = "true"
uglyURLs = "true"
publishDir = "docs"

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
custom_theme = "customblack.css"

[markup.goldmark.renderer]
unsafe= true
